//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CogwheelSlimDX.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CogwheelSlimDX.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ; General buttons:
        ///Space=&gt;0.Start;0.Pause
        ///Back=&gt;0.Reset
        ///
        ///; Player 1 joypad:
        ///Up=&gt;0.Up
        ///Down=&gt;0.Down
        ///Left=&gt;0.Left
        ///Right=&gt;0.Right
        ///ControlKey=&gt;0.Trigger1
        ///Menu=&gt;0.Trigger2
        ///
        ///; Player 2 joypad:
        ///Home=&gt;1.Up
        ///End=&gt;1.Down
        ///Delete=&gt;1.Left
        ///PageDown=&gt;1.Right
        ///Insert=&gt;1.Trigger1
        ///PageUp=&gt;1.Trigger2
        ///
        ///; Player 1 number pad:
        ///D0=&gt;0.Number0
        ///D1=&gt;0.Number1
        ///D2=&gt;0.Number2
        ///D3=&gt;0.Number3
        ///D4=&gt;0.Number4
        ///D5=&gt;0.Number5
        ///D6=&gt;0.Number6
        ///D7=&gt;0.Number7
        ///D8=&gt;0.Number8
        ///D9=&gt;0.Number9
        ///OemMinus=&gt;0.Star
        ///Oemplus=&gt;0.Hash
        ///
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Config_DefaultKeyMapping {
            get {
                return ResourceManager.GetString("Config_DefaultKeyMapping", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Flag_BR {
            get {
                object obj = ResourceManager.GetObject("Flag_BR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Flag_DE {
            get {
                object obj = ResourceManager.GetObject("Flag_DE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Flag_EN {
            get {
                object obj = ResourceManager.GetObject("Flag_EN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Flag_ES {
            get {
                object obj = ResourceManager.GetObject("Flag_ES", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Flag_FR {
            get {
                object obj = ResourceManager.GetObject("Flag_FR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Flag_IT {
            get {
                object obj = ResourceManager.GetObject("Flag_IT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Flag_JP {
            get {
                object obj = ResourceManager.GetObject("Flag_JP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Flag_KR {
            get {
                object obj = ResourceManager.GetObject("Flag_KR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Flag_NZ {
            get {
                object obj = ResourceManager.GetObject("Flag_NZ", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Flag_US {
            get {
                object obj = ResourceManager.GetObject("Flag_US", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;style&gt;
        ///a { color: #36F; text-decoration: none; }
        ///a:hover { color: #33F; text-decoration: underline; }
        ///td, th { padding: 2px; text-align: left; vertical-align: top; border: 1px solid #999; }
        ///table { border-collapse: collapse; width: 100%; }
        ///&lt;/style&gt;
        ///&lt;p&gt;Written by &lt;a href=&quot;mailto:benryves@benryves.com&quot;&gt;Ben Ryves&lt;/a&gt; 2006-2008.&lt;/p&gt;
        ///&lt;p style=&quot;font-weight: bold;&quot;&gt;Contributors&lt;/p&gt;
        ///&lt;ul&gt;
        ///	&lt;li&gt;waveOut API wrapper written by &lt;a href=&quot;http://www.chronotron.com/&quot;&gt;Ianier Munoz&lt;/a&gt;.&lt;/li&gt;
        ///	&lt;li&gt;White noise parit [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Html_About {
            get {
                return ResourceManager.GetString("Html_About", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Icon_ArrowDown {
            get {
                object obj = ResourceManager.GetObject("Icon_ArrowDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icon_ArrowLeft {
            get {
                object obj = ResourceManager.GetObject("Icon_ArrowLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icon_ArrowRight {
            get {
                object obj = ResourceManager.GetObject("Icon_ArrowRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icon_ArrowUp {
            get {
                object obj = ResourceManager.GetObject("Icon_ArrowUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icon_Bug {
            get {
                object obj = ResourceManager.GetObject("Icon_Bug", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icon_Camera {
            get {
                object obj = ResourceManager.GetObject("Icon_Camera", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icon_Comment {
            get {
                object obj = ResourceManager.GetObject("Icon_Comment", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icon_CommentEdit {
            get {
                object obj = ResourceManager.GetObject("Icon_CommentEdit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icon_Controller {
            get {
                object obj = ResourceManager.GetObject("Icon_Controller", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icon_Error {
            get {
                object obj = ResourceManager.GetObject("Icon_Error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icon_Exclamation {
            get {
                object obj = ResourceManager.GetObject("Icon_Exclamation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icon_GameGenie {
            get {
                object obj = ResourceManager.GetObject("Icon_GameGenie", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icon_House {
            get {
                object obj = ResourceManager.GetObject("Icon_House", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icon_Information {
            get {
                object obj = ResourceManager.GetObject("Icon_Information", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icon_Joystick {
            get {
                object obj = ResourceManager.GetObject("Icon_Joystick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icon_Keyboard {
            get {
                object obj = ResourceManager.GetObject("Icon_Keyboard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icon_Lightning {
            get {
                object obj = ResourceManager.GetObject("Icon_Lightning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icon_Monitor {
            get {
                object obj = ResourceManager.GetObject("Icon_Monitor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icon_SmsRom {
            get {
                object obj = ResourceManager.GetObject("Icon_SmsRom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icon_Sound {
            get {
                object obj = ResourceManager.GetObject("Icon_Sound", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icon_SoundLow {
            get {
                object obj = ResourceManager.GetObject("Icon_SoundLow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icon_SoundMute {
            get {
                object obj = ResourceManager.GetObject("Icon_SoundMute", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icon_SoundNone {
            get {
                object obj = ResourceManager.GetObject("Icon_SoundNone", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icon_TimeGo {
            get {
                object obj = ResourceManager.GetObject("Icon_TimeGo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icon_User {
            get {
                object obj = ResourceManager.GetObject("Icon_User", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icon_Wrench {
            get {
                object obj = ResourceManager.GetObject("Icon_Wrench", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_Banner {
            get {
                object obj = ResourceManager.GetObject("Image_Banner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
