//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CogwheelSlimDX.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CogwheelSlimDX.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Flag_BR {
            get {
                object obj = ResourceManager.GetObject("Flag_BR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Flag_DE {
            get {
                object obj = ResourceManager.GetObject("Flag_DE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Flag_EN {
            get {
                object obj = ResourceManager.GetObject("Flag_EN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Flag_ES {
            get {
                object obj = ResourceManager.GetObject("Flag_ES", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Flag_FR {
            get {
                object obj = ResourceManager.GetObject("Flag_FR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Flag_IT {
            get {
                object obj = ResourceManager.GetObject("Flag_IT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Flag_JP {
            get {
                object obj = ResourceManager.GetObject("Flag_JP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Flag_KR {
            get {
                object obj = ResourceManager.GetObject("Flag_KR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Flag_NZ {
            get {
                object obj = ResourceManager.GetObject("Flag_NZ", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Flag_US {
            get {
                object obj = ResourceManager.GetObject("Flag_US", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Written by &lt;a href=&quot;mailto:benryves@benryves.com&quot;&gt;Ben Ryves&lt;/a&gt; 2006-2007&lt;/p&gt;
        ///&lt;p&gt;The following references were used in writing this software. 
        ///Most can be downloaded from the documentation section of &lt;a href=&quot;http://bee-dev.com/?go=smsp&quot;&gt;SMS Power!&lt;/a&gt; or on the author&apos;s own site.&lt;/p&gt;
        ///&lt;ul&gt;
        ///    &lt;li&gt;&lt;a href=&quot;http://bee-dev.com/?go=cmcd&quot;&gt;Charles MacDonald&lt;/a&gt;
        ///        &lt;ul&gt;
        ///            &lt;li&gt;SMS/GG hardware notes.&lt;/li&gt;
        ///            &lt;li&gt;Sega SC-3000H hardware notes.&lt;/li&gt;
        ///            &lt;li&gt;Sega Master System [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Html_About {
            get {
                return ResourceManager.GetString("Html_About", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Icon_Bug {
            get {
                object obj = ResourceManager.GetObject("Icon_Bug", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icon_Camera {
            get {
                object obj = ResourceManager.GetObject("Icon_Camera", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icon_Comment {
            get {
                object obj = ResourceManager.GetObject("Icon_Comment", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icon_CommentEdit {
            get {
                object obj = ResourceManager.GetObject("Icon_CommentEdit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icon_Controller {
            get {
                object obj = ResourceManager.GetObject("Icon_Controller", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icon_Error {
            get {
                object obj = ResourceManager.GetObject("Icon_Error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icon_Exclamation {
            get {
                object obj = ResourceManager.GetObject("Icon_Exclamation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icon_GameGenie {
            get {
                object obj = ResourceManager.GetObject("Icon_GameGenie", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icon_House {
            get {
                object obj = ResourceManager.GetObject("Icon_House", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icon_Information {
            get {
                object obj = ResourceManager.GetObject("Icon_Information", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icon_Joystick {
            get {
                object obj = ResourceManager.GetObject("Icon_Joystick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icon_Keyboard {
            get {
                object obj = ResourceManager.GetObject("Icon_Keyboard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icon_Lightning {
            get {
                object obj = ResourceManager.GetObject("Icon_Lightning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icon_SmsRom {
            get {
                object obj = ResourceManager.GetObject("Icon_SmsRom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icon_User {
            get {
                object obj = ResourceManager.GetObject("Icon_User", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icon_Wrench {
            get {
                object obj = ResourceManager.GetObject("Icon_Wrench", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_Banner {
            get {
                object obj = ResourceManager.GetObject("Image_Banner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
