//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeeDevelopment.Cogwheel.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.bee-dev.com/?go=cogwheel.bugs")]
        public string UrlBugReport {
            get {
                return ((string)(this["UrlBugReport"]));
            }
            set {
                this["UrlBugReport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OptionSimulateGameGearLcdScaling {
            get {
                return ((bool)(this["OptionSimulateGameGearLcdScaling"]));
            }
            set {
                this["OptionSimulateGameGearLcdScaling"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.bee-dev.com/?go=cogwheel")]
        public string UrlWebsite {
            get {
                return ((string)(this["UrlWebsite"]));
            }
            set {
                this["UrlWebsite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OptionLinearInterpolation {
            get {
                return ((bool)(this["OptionLinearInterpolation"]));
            }
            set {
                this["OptionLinearInterpolation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OptionEnableSound {
            get {
                return ((bool)(this["OptionEnableSound"]));
            }
            set {
                this["OptionEnableSound"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StoredPathQuickLoad {
            get {
                return ((string)(this["StoredPathQuickLoad"]));
            }
            set {
                this["StoredPathQuickLoad"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StoredPathState {
            get {
                return ((string)(this["StoredPathState"]));
            }
            set {
                this["StoredPathState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StoredPathAdvancedCartridge {
            get {
                return ((string)(this["StoredPathAdvancedCartridge"]));
            }
            set {
                this["StoredPathAdvancedCartridge"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StoredPathAdvancedCartridgePatch {
            get {
                return ((string)(this["StoredPathAdvancedCartridgePatch"]));
            }
            set {
                this["StoredPathAdvancedCartridgePatch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StoredPathAdvancedBios {
            get {
                return ((string)(this["StoredPathAdvancedBios"]));
            }
            set {
                this["StoredPathAdvancedBios"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int OptionMaxMRUEntries {
            get {
                return ((int)(this["OptionMaxMRUEntries"]));
            }
            set {
                this["OptionMaxMRUEntries"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StoredPathMRU {
            get {
                return ((string)(this["StoredPathMRU"]));
            }
            set {
                this["StoredPathMRU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OptionMaintainAspectRatio {
            get {
                return ((bool)(this["OptionMaintainAspectRatio"]));
            }
            set {
                this["OptionMaintainAspectRatio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OptionEnableFMSound {
            get {
                return ((bool)(this["OptionEnableFMSound"]));
            }
            set {
                this["OptionEnableFMSound"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.3")]
        public float InputJoystickAxisThreshold {
            get {
                return ((float)(this["InputJoystickAxisThreshold"]));
            }
            set {
                this["InputJoystickAxisThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.3")]
        public float InputXInputAxisThreshold {
            get {
                return ((float)(this["InputXInputAxisThreshold"]));
            }
            set {
                this["InputXInputAxisThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.3")]
        public float InputXInputTriggerThreshold {
            get {
                return ((float)(this["InputXInputTriggerThreshold"]));
            }
            set {
                this["InputXInputTriggerThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool InputSkipDuplicatedXInputJoysticks {
            get {
                return ((bool)(this["InputSkipDuplicatedXInputJoysticks"]));
            }
            set {
                this["InputSkipDuplicatedXInputJoysticks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LeftEyeOnly")]
        public string Option3DGlasses {
            get {
                return ((string)(this["Option3DGlasses"]));
            }
            set {
                this["Option3DGlasses"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16711680")]
        public int Option3DGlassesLeftFilterColour {
            get {
                return ((int)(this["Option3DGlassesLeftFilterColour"]));
            }
            set {
                this["Option3DGlassesLeftFilterColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("65535")]
        public int Option3DGlassesRightFilterColour {
            get {
                return ((int)(this["Option3DGlassesRightFilterColour"]));
            }
            set {
                this["Option3DGlassesRightFilterColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Option3DGlassesLeftEyeFirst {
            get {
                return ((bool)(this["Option3DGlassesLeftEyeFirst"]));
            }
            set {
                this["Option3DGlassesLeftEyeFirst"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OptionRegionAutomatic {
            get {
                return ((bool)(this["OptionRegionAutomatic"]));
            }
            set {
                this["OptionRegionAutomatic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OptionRegionJapanese {
            get {
                return ((bool)(this["OptionRegionJapanese"]));
            }
            set {
                this["OptionRegionJapanese"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OptionVideoStandardAutomatic {
            get {
                return ((bool)(this["OptionVideoStandardAutomatic"]));
            }
            set {
                this["OptionVideoStandardAutomatic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OptionVideoStandardNtsc {
            get {
                return ((bool)(this["OptionVideoStandardNtsc"]));
            }
            set {
                this["OptionVideoStandardNtsc"] = value;
            }
        }
    }
}
