//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CogwheelSlimDX.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Up")]
        public global::System.Windows.Forms.Keys KeyP1Up {
            get {
                return ((global::System.Windows.Forms.Keys)(this["KeyP1Up"]));
            }
            set {
                this["KeyP1Up"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Down")]
        public global::System.Windows.Forms.Keys KeyP1Down {
            get {
                return ((global::System.Windows.Forms.Keys)(this["KeyP1Down"]));
            }
            set {
                this["KeyP1Down"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Left")]
        public global::System.Windows.Forms.Keys KeyP1Left {
            get {
                return ((global::System.Windows.Forms.Keys)(this["KeyP1Left"]));
            }
            set {
                this["KeyP1Left"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Right")]
        public global::System.Windows.Forms.Keys KeyP1Right {
            get {
                return ((global::System.Windows.Forms.Keys)(this["KeyP1Right"]));
            }
            set {
                this["KeyP1Right"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ControlKey")]
        public global::System.Windows.Forms.Keys KeyP1TL {
            get {
                return ((global::System.Windows.Forms.Keys)(this["KeyP1TL"]));
            }
            set {
                this["KeyP1TL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Menu")]
        public global::System.Windows.Forms.Keys KeyP1TR {
            get {
                return ((global::System.Windows.Forms.Keys)(this["KeyP1TR"]));
            }
            set {
                this["KeyP1TR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Space")]
        public global::System.Windows.Forms.Keys KeyStart {
            get {
                return ((global::System.Windows.Forms.Keys)(this["KeyStart"]));
            }
            set {
                this["KeyStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Space")]
        public global::System.Windows.Forms.Keys KeyPause {
            get {
                return ((global::System.Windows.Forms.Keys)(this["KeyPause"]));
            }
            set {
                this["KeyPause"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Back")]
        public global::System.Windows.Forms.Keys KeyReset {
            get {
                return ((global::System.Windows.Forms.Keys)(this["KeyReset"]));
            }
            set {
                this["KeyReset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::System.Windows.Forms.Keys KeyP2Up {
            get {
                return ((global::System.Windows.Forms.Keys)(this["KeyP2Up"]));
            }
            set {
                this["KeyP2Up"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::System.Windows.Forms.Keys KeyP2Down {
            get {
                return ((global::System.Windows.Forms.Keys)(this["KeyP2Down"]));
            }
            set {
                this["KeyP2Down"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::System.Windows.Forms.Keys KeyP2Left {
            get {
                return ((global::System.Windows.Forms.Keys)(this["KeyP2Left"]));
            }
            set {
                this["KeyP2Left"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::System.Windows.Forms.Keys KeyP2Right {
            get {
                return ((global::System.Windows.Forms.Keys)(this["KeyP2Right"]));
            }
            set {
                this["KeyP2Right"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::System.Windows.Forms.Keys KeyP2TL {
            get {
                return ((global::System.Windows.Forms.Keys)(this["KeyP2TL"]));
            }
            set {
                this["KeyP2TL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::System.Windows.Forms.Keys KeyP2TR {
            get {
                return ((global::System.Windows.Forms.Keys)(this["KeyP2TR"]));
            }
            set {
                this["KeyP2TR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.bee-dev.com/?go=cogwheel.bugs")]
        public string UrlBugReport {
            get {
                return ((string)(this["UrlBugReport"]));
            }
            set {
                this["UrlBugReport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OptionSimulateGameGearLcdScaling {
            get {
                return ((bool)(this["OptionSimulateGameGearLcdScaling"]));
            }
            set {
                this["OptionSimulateGameGearLcdScaling"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.bee-dev.com/?go=cogwheel")]
        public string UrlWebsite {
            get {
                return ((string)(this["UrlWebsite"]));
            }
            set {
                this["UrlWebsite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OptionLinearInterpolation {
            get {
                return ((bool)(this["OptionLinearInterpolation"]));
            }
            set {
                this["OptionLinearInterpolation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OptionEnableSound {
            get {
                return ((bool)(this["OptionEnableSound"]));
            }
            set {
                this["OptionEnableSound"] = value;
            }
        }
    }
}
